apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-1
  namespace: gitapps
spec:
  selector:
    matchLabels:
      app: nginx-1
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx-1
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
