apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons-nginx
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          # Git generator, 'child' #1
          - git:
              repoURL: https://github.com/urbanmassage/gitops-testing
              revision: HEAD
              directories:
                - path: deploy/*
          # cluster generator, 'child' #2
          - list:
              elements:
                - cluster: urban-prod
                  url: https://kubernetes.default.svc
                  values:
                    project: webservers
                - cluster: urban-stag
                  url: https://35.233.72.187
                  values:
                    project: webservers
  template:
    metadata:
      name: '{{.path.basename}}-{{.cluster}}'
    spec:
      project: "webservers"
      source:
        repoURL: https://github.com/urbanmassage/gitops-testing
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: '{{.url}}'
        namespace: '{{.path.basename}}'