apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.guestbook.appName }}
  namespace: gitapps
spec:
  replicas: {{ .Values.guestbook.replicaCount }}
  selector:
    matchLabels:
      app: frontend 
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: phico/frontend:1.1
        imagePullPolicy: Always
        name: frontend
        ports:
        - name: frontend
          containerPort: 4200

